apiVersion: apps/v1
kind: Deployment
metadata:
  name: podpulse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: podpulse
  template:
    metadata:
      labels:
        app: podpulse
    spec:
      containers:
        - name: podpulse
          image: podpulse:v1
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10